Mirrorful/mirrorful

- packages/mirrorful/editor/next.config.js
- packages/mirrorful/editor/package.json
- packages/mirrorful/editor/src/pages/api/store.ts
- packages/mirrorful/editor/yarn.lock
- packages/mirrorful/index.ts
- packages/mirrorful/init.ts
- packages/mirrorful/package.json
- packages/mirrorful/tsconfig.json
Resolves #42, #40, and fix store.json error
> Resolves #42, #40, and fix store.json error

- packages/mirrorful/cli/init.ts
- packages/mirrorful/editor/src/components/ColorPalette/ColorPaletteSection.tsx
- packages/mirrorful/editor/src/components/Dashboard.tsx
- packages/mirrorful/editor/src/pages/api/store.ts
- Create store.json in CLI if it does not exist
- Do not let colorData even be undefined, instead coalesce it to `[]`
> fix: "Choose my own theme" button not working 

- .mirrorful/store/config.json
- packages/mirrorful/cli/init.ts
- packages/mirrorful/editor/src/components/Dashboard.tsx
- packages/mirrorful/package.json
- packages/mirrorful/yarn.lock
Reverts Mirrorful/mirrorful#88
> Revert "3.0.9: Use installed path in CLI"

- packages/mirrorful/editor/src/components/ColorPalette/ColorPaletteSection.tsx
- packages/mirrorful/editor/src/components/Dashboard.tsx
- packages/mirrorful/editor/src/components/Onboarding/index.tsx
- packages/mirrorful/editor/src/components/Typography/EditFontSizeModal.tsx
- packages/mirrorful/editor/src/components/Typography/FontSizeRow.tsx
- packages/mirrorful/editor/src/components/Typography/FontSizesSection.tsx
- packages/mirrorful/editor/src/components/Typography/TypographySection.tsx
- packages/mirrorful/editor/src/pages/api/export.ts
- packages/mirrorful/editor/src/store/migrations.ts
- packages/mirrorful/editor/src/store/store.ts
- packages/mirrorful/editor/src/types.ts
Supporting `fontSizes`.
Export looks something like:
> Add font sizes

- i18n/README.de.md
- minor grammar fixes
- updates path to new image in Stay Up-to-Date section
> Updates README.de.md

- README.md
- i18n/README.sv.md
- Add translation file in `i18n`
- links from top-level README to Swedish README.sv.md
> Swedish translation (i18n/README.sv.md)

- README.md
This PR fixes a few grammar issues I noticed in the README.
> docs: update README grammar

- packages/mirrorful/cli/helpers/openBrowser.ts
- packages/mirrorful/cli/helpers/sleep.ts
- packages/mirrorful/cli/init.ts
- packages/mirrorful/openBrowser.mjs
- packages/mirrorful/package.json
- packages/mirrorful/yarn.lock
Made a simple open browser feature following the create-react-app library. #127
> Open localhost:5050 automatically when running mirrorful cli

- README.md
- i18n/README.tr.md
Hey, 
just wanted to let you know that I only translated the README file and not the UI or any other pages, as @alexdanilowicz mentioned in their comment on this GitHub issue (https://github.com/Mirrorful/mirrorful/issues/18#issuecomment-1448719872), 
thanks!
> Translate README file to Turkish

- packages/mirrorful/editor/src/components/Typography/EditFontSizeModal.tsx
- packages/mirrorful/editor/src/components/Typography/FontSizeRow.tsx
- packages/mirrorful/editor/src/components/Typography/FontSizesSection.tsx
Solves this issue https://github.com/Mirrorful/mirrorful/issues/154
> Modal title fixed

- packages/mirrorful/editor/src/components/ColorPalette/ColorPaletteSection.tsx
This is a maintenance PR to remove commented out code that made its way into main (sorry about that).
> Removed commented out code

- packages/core/src/components/Dashboard/index.tsx
- packages/core/src/components/Typography/FontSizeRow.tsx
I'm not sure this is the best practice but I checked Colors section too, both works same. Fixes #181
> Typography section overlap fix

- packages/core/src/components/Dashboard/index.tsx
- packages/mirrorful/editor/yarn.lock
https://www.loom.com/share/e4ada435d0504d7f9af8af07c293f7aa
I think underlying issue is usage of width vs minwidth
> Fix navbar issue

- packages/core/src/components/Dashboard/Sidebar.tsx
> fix: update sidebar title

- packages/core/src/components/ColorPalette/ColorDisplay.tsx
Created the copied feature #241. Here is a loom of the changes https://www.loom.com/share/e02d326fa4884ec195252a48289c493a
> Add copy color feature

- packages/core/src/components/ColorPalette/ColorDisplay.tsx
> Added hover effect on color copy

- packages/core/src/components/ColorPalette/ColorDisplay.tsx
- packages/core/src/components/ColorPalette/ColorPaletteSection.tsx
- packages/core/src/components/Dashboard/index.tsx
- packages/core/src/components/Onboarding/pages/Referral.tsx
- packages/core/src/components/Shadows/ShadowsSection.tsx
> Add copy to clipboard function for shadows

- packages/core/src/components/Shadows/ShadowsSection.tsx
- packages/core/src/components/Typography/FontSizeRow.tsx
- packages/mirrorful/editor/yarn.lock
> Use nooflines prop to truncate titles 

- packages/core/src/translators/index.ts
- packages/core/src/translators/toTs.ts
> Included dynamic types in the export config

- integrations/figma/mirrorful-plugin/.gitignore
- integrations/figma/mirrorful-plugin/README.md
- integrations/figma/mirrorful-plugin/code.ts
- integrations/figma/mirrorful-plugin/manifest.json
- integrations/figma/mirrorful-plugin/package-lock.json
- integrations/figma/mirrorful-plugin/package.json
- integrations/figma/mirrorful-plugin/tsconfig.json
> Figma Plugin Init

- packages/core/src/components/ExportSettingsModal.tsx
> export - all file types on by default

- packages/core/src/components/Typography/DisplayFontProperty.tsx
- packages/core/src/components/Typography/FontPropertyRow.tsx
- packages/core/src/components/Typography/FontSize/FontSizeRow.tsx
- packages/core/src/components/Typography/FontSize/FontSizesSection.tsx
- packages/core/src/components/Typography/FontWeight/FontWeightRow.tsx
- packages/core/src/components/Typography/FontWeight/FontWeightSection.tsx
- packages/core/src/components/Typography/LineHeight/LineHeightData.tsx
- packages/core/src/components/Typography/LineHeight/LineHeightSection.tsx
- packages/core/src/components/Typography/TypographySection.tsx
> feat: allow user to use custom placeholder to test out the typographies

- packages/core/src/components/Sidebar/Sidebar.tsx
Resolves #334 
@alexdanilowicz Please let me know what you think.
> Sidebar items are now hyperlinks

- packages/mirrorful/editor/package.json
- packages/mirrorful/editor/yarn.lock
- packages/mirrorful/package.json
- yarn.lock
Resolves https://github.com/Mirrorful/mirrorful/issues/359
> Add yarn and sharp as deps

- docs/home/examples.mdx
I changed the link because it was a duplicate.
Please let me know if the deletion is better or if the link is wrong.
#369
> With Next.js link change to linear-example

- README.md
- docs/home/get-started.mdx
- i18n/README.de.md
- i18n/README.es.md
- i18n/README.no.md
- i18n/README.pt.md
- i18n/README.sv.md
- i18n/README.tr.md
- packages/mirrorful/README.md
Added pnpm docs on multiple places including README.md and getting started docs.
#386
> feat: Added pnpm in docs

- apps/web/.eslintrc.json
- apps/web/src/hooks/useLocalStorage.ts
- packages/core/.eslintrc.json
- packages/core/src/components/ColorPalette/AddColorModal.tsx
- packages/core/src/components/ColorPalette/EditBaseColorModal.tsx
- packages/core/src/components/ColorPalette/utils.ts
- packages/core/src/components/Shadows/EditShadowModal.tsx
- packages/core/src/components/Typography/FontSize/EditFontSizeModal.tsx
Reference: https://mirrorful.slack.com/archives/C04RR2D7C65/p1683770775020169?thread_ts=1683769489.423339&cid=C04RR2D7C65
This would prevent unnecessary console logs in our app. If we want to keep a specific log for debugging, we can always eslint-disable the corresponding line.
> chore: update eslint config for web, core to show warnings for stray logs

- packages/core/src/components/Shadows/EditShadowModal.tsx
> fix: prevent 'unique key prop' on shadows page

- packages/core/src/components/Onboarding/OnboardingContainer.tsx
- packages/core/src/components/Onboarding/pages/NamePrimary.tsx
- packages/core/src/components/Onboarding/pages/OtherColors.tsx
- packages/core/src/components/Onboarding/pages/Referral.tsx
- packages/core/src/components/Onboarding/pages/ReviewPrimary.tsx
> improv: make the onboarding flow mobile compatible

- packages/core/src/components/Typography/FontPropertyRow.tsx
- packages/core/src/components/Typography/FontSize/EditFontSizeModal.tsx
- packages/core/src/components/Typography/FontSize/FontSizeRow.tsx
- packages/core/src/components/Typography/FontWeight/FontWeightRow.tsx
- packages/core/src/components/Typography/LineHeight/LineHeightData.tsx
- packages/core/src/components/Typography/TypographySection.tsx
> Made Typography view responsive

- packages/core/src/components/Shadows/EditShadowModal.tsx
- packages/core/src/components/Shadows/ShadowColorPicker.tsx
- packages/core/src/components/Shadows/ShadowsSection.tsx
> Made shadows view responsive

- packages/core/src/components/ColorPalette/AddColorModal.tsx
- packages/core/src/components/ColorPalette/ColorDisplay.tsx
- packages/core/src/components/ColorPalette/EditBaseColorModal.tsx
- packages/core/src/components/ColorPalette/VariantRow.tsx
- packages/core/src/components/Layout.tsx
- packages/core/src/pages/ColorsPage.tsx
- packages/core/src/pages/ShadowsPage.tsx
- packages/core/src/pages/ThemeEditorPage.tsx
- packages/core/src/pages/ThemesPage.tsx
- packages/core/src/pages/TypographyPage.tsx
- packages/mirrorful/editor/src/pages/_app.tsx
Reverts Mirrorful/mirrorful#423
> Revert "Fixing Re-renders"

- apps/web/package.json
- packages/server/package.json
- yarn.lock
https://github.com/getsentry/sentry-javascript/releases
> Upgrade sentry to 7.53.0 to fix windows error

- docs/home/contributing.mdx
Hello @alexdanilowicz please review my pull request for issue #502
> fix typo on contributing guide

- packages/core/src/components/ColorPalette/ColorDisplay.tsx
- packages/core/src/components/ColorPalette/EditColorNameModal.tsx
Fixes #484 
Reverts part of https://github.com/Mirrorful/mirrorful/pull/433
> feat: add rename color to color display dropdown to allow mobile users to rename colors
