Mirrorful/mirrorful

- packages/mirrorful/editor/src/components/ColorPalette/ColorPaletteSection.tsx
- packages/mirrorful/editor/src/components/ColorPalette/EditColorModal.tsx
This PR fixes the primary/secondary color persistence issue reported in #31.
Current color editor behavior: https://www.loom.com/share/6a0c392eae12442d865b87058c33c030
Behavior with fixes in this PR: https://www.loom.com/share/50b6590fce7f49d68f859e224b5cabd6
`<EditColorModal />` has two stateful `isPrimary` and `isSecondary` values whose [initial values come from `initialColorData`](https://github.com/zachsnoek/mirrorful/blob/3c7fa2ede409c380d33031f5136d9a4dc5e405d5/packages/mirrorful/editor/src/components/ColorPalette/EditColorModal.tsx#L54-L59). When the modal closes, [they get passed to `onClose`](https://github.com/zachsnoek/mirrorful/blob/3c7fa2ede409c380d33031f5136d9a4dc5e405d5/packages/mirrorful/editor/src/components/ColorPalette/EditColorModal.tsx#L136-L137), which updates the …
> fix: ensure primary/secondary color persists

- README.md
- i18n/README.de.md
- adds German top-level README.de.md
- links from top-level README to German README.de.md
**Notice**
Missing the following two READMEs --> `package/mirrorful` directory, and the UI itself in `package/mirrorful/editor`. 
I would suggest putting it in a follow-up ticket when the i18n gets setup. 
I am curious about your feedback. What do you think?
> i18n - german translation of main README.de.md

- packages/mirrorful/cli/init.ts
- packages/mirrorful/editor/package.json
- packages/mirrorful/editor/src/export.ts
- packages/mirrorful/editor/src/pages/api/export.ts
- packages/mirrorful/editor/src/pages/api/store.ts
- packages/mirrorful/editor/src/storeUtils.ts
- packages/mirrorful/editor/yarn.lock
- packages/mirrorful/package.json
- packages/mirrorful/yarn.lock
Refactoring `store.json` to use `conf` package instead.
Added logic to migrate old `store.json` files to use `conf` storage instead.
Tested with existing projects + starting with a new `.mirrorful` folder.
> Refactor to use `conf`

- packages/mirrorful/cli/init.ts
- packages/mirrorful/editor/package.json
- packages/mirrorful/yarn.lock
I accidentally broke non-next js apps by using the next command in the .bin folder, so now there are two commands, one for next apps, one for react apps.
> Fix package to work on non-NextJS apps

- packages/mirrorful/editor/src/components/ColorPalette/EditColorModal.tsx
**Summary**
Pull request to fix issue 66.  This PR changes setShowBaseColorPicker default from false to true, to ensure the colorpicker is displayed correctly when the edit color modal is opened.
**Description**
When a color in the editor is opened for edit, the EditColorModal doesn't initially display the colorpicker.  This is a result of no color (base / hover / active) being assigned to be displayed in the colorpicker.  This PR changes the `setShowBaseColorPicker` to default to true, thus ensuring that when the edit modal is displayed, the base color appears in the color picker.
> Change EditColorModal showBaseColorPicker default to true from false

- packages/mirrorful/editor/src/components/ColorPalette/ColorPicker.tsx
- packages/mirrorful/editor/src/components/ColorPalette/EditColorModal.tsx
- packages/mirrorful/editor/src/components/ColorPalette/utils.ts
Demo: https://www.loom.com/share/d721fd16dcdd49fc8123c5ac4fa45bc9
This PR addresses #57: It adds magic wand icon buttons in the hover and active inputs, allowing users to fill the input with a recommended shade.
I also noticed that the `<ColorPicker />` alignment is a bit funky because the underlying `<SketchPicker />` has `box-sizing: content-box`. I changed it to `border-box` so that it's easier to work with and updated the modal layout to two equally-sized columns.
> feat: add recommended shade buttons

- packages/mirrorful/editor/src/components/ColorPalette/ColorRow.tsx
Summary
Pull request to fix issue 59. This PR adds check for isPrimary and isSecondary on the buttons and changes text based on this condition.
Description
When a color is Set as Primary, it's attribute isPrimary is set to true, and based on this attribute, we disable the 'Set as Primary' button and also change it's text to 'Already Primary'. Same happens for Set as Secondary button.
Here's a small video showing how it looks on screen - 
https://watch.screencastify.com/v/tHwXBcOyT7rnnqppjffq
> resolves https://github.com/Mirrorful/mirrorful/issues/59

- packages/mirrorful/editor/src/components/ColorPalette/AddVariantModal.tsx
- packages/mirrorful/editor/src/components/ColorPalette/EditVariantModal.tsx
**Summary**
This PR is a fix for issue #82.  Previously, saving a new or edited variant color would permit, and save, invalid CSS color values.  This fix adds error checking and Input highlighting prior to save, following the same convention as in the onboarding name page.
**Description**
Implementation is the same in both the `AddVariantModal` and the `EditVariantModal` in that an error variable is created, and used to highlight incorrect / missing syntax on the color inputs within the modal.  A new Text Chakra component is added beneath each input to display relevant error message.
The validation is done by saving the initial value, and applying the handleInvalidCss util to the input color, then checking for differences, and setting the error message in the event that there is a …
> Issue #82 - Handle invalid colors in variant modals

- packages/mirrorful/editor/src/components/Typography/EditFontSizeModal.tsx
Fixes #104 by updating the Chakra-ui Input to having type "number", which permits entering (only one) decimal place, which wasn't permitted previously.
> Updated EditFontSizeModal variant value input to 'number' type

- packages/mirrorful/editor/src/pages/api/export.ts
- packages/mirrorful/package.json
Resolves: https://github.com/Mirrorful/mirrorful/issues/108
Future food for thought:
We could expand this to a structure like:
```
{
palette: {
colors: {
red: '#fffff",  
},
neutrals: {
gray: '#d3d3d3',
},
alphas: {
white: rgba(255, 255, 255, 0.3),
},
}
}
```
> Export object reshape

- packages/mirrorful/editor/src/components/ExportSuccessModal.tsx
- packages/mirrorful/editor/src/components/Onboarding/pages/ImportInstructions.tsx
Resolves: [#115 ](https://github.com/Mirrorful/mirrorful/issues/115)
- Added option & instructions for tailwind css in the export modal
> Added tailwind css option in the export modal

- packages/mirrorful/editor/src/components/ColorPalette/EditColorModal.tsx
This PR addresses #142: it clears the `<EditColorModal />` state on close.
Before: https://www.loom.com/share/1080d75392504e6ea7b73c5f3d0bc87b
After: https://www.loom.com/share/d6ecb2261f90403da520f6b390cb01d5
> fix: reset color modal state on close

- packages/mirrorful/editor/src/store/migrations.ts
- packages/mirrorful/editor/src/store/store.ts
- packages/mirrorful/editor/src/types.ts
This PR sets us up for letting users select which file types to export (#147). It adds a `files` property to the configuration object and a corresponding migration. In my next PR, we'll add an input in the editor for setting this property and only export to the specified files.
Manual testing: Exported to a configuration file at the migration version `0.0.3` and ensured that the migration version was incremented and a `files` property was created.
> feat: add files property to configuration object

- packages/mirrorful/editor/src/components/Typography/EditFontSizeModal.tsx
While I was on issue #113 I noticed that it was tricky to edit the variant value. Whenever you delete the current value it add a zero to the left. Here is an example: 
With this update, the user would be able to edit the variant value without getting a zero at the left of the input field. It would look like this instead.
> Remove leading zeros when deleting a variant value

- packages/mirrorful/editor/src/components/Dashboard.tsx
- packages/mirrorful/editor/src/components/ExportSuccessModal.tsx
- packages/mirrorful/editor/src/components/Onboarding/index.tsx
- packages/mirrorful/editor/src/components/Onboarding/pages/ImportInstructions.tsx
Resolves: [#157  ](https://github.com/Mirrorful/mirrorful/issues/157)
- replaced hardcoded primary color name from onboarding and export modal by actual color name see by user
- fixed deprecated tokens usage synatx and structured it as per mirrorful v4.0.0 release
Reference:
[Loom Video](https://www.loom.com/share/22673c9ec4cc4600bac9e0b01bc0f0f9)
> Replaced hardcoded color name from onboarding and export modal by actual color name

- packages/mirrorful/editor/src/pages/api/export.ts
- packages/mirrorful/editor/src/store/migrations.ts
- packages/mirrorful/editor/src/translators/createThemeObject.ts
- packages/mirrorful/editor/src/translators/index.ts
- packages/mirrorful/editor/src/translators/sanitizeName.ts
- packages/mirrorful/editor/src/translators/toCjs.ts
- packages/mirrorful/editor/src/translators/toCss.ts
- packages/mirrorful/editor/src/translators/toJs.ts
- packages/mirrorful/editor/src/translators/toJson.ts
- packages/mirrorful/editor/src/translators/toScss.ts
- packages/mirrorful/editor/src/translators/types.ts
- packages/mirrorful/editor/src/types.ts
- packages/mirrorful/editor/src/utils/getKeys.ts
Currently, two file generation functions in the export API handler are responsible for generating all six token files. While this works fine now, it'll become hard to navigate and maintain ~if~ when we start supporting more export types. The current implementation also makes it more difficult to generate specific file types.
Instead, we should have functions that handle the content translation for each file type. This PR introduces translator functions for the six file types and replaces the current handler implementation. These signatures are probably incomplete but should be enough to help us add new export types more quickly, and with my next PR (addressing #147), that will use the config to determine which files to generate.
The easiest way to review this is by reviewing each commit. …
> refactor: add file type translators

- packages/mirrorful/.husky/pre-commit
- packages/mirrorful/editor/src/components/Onboarding/pages/ImportInstructions.tsx
- packages/mirrorful/package.json
- packages/mirrorful/yarn.lock
Resolves: [#158 ](https://github.com/Mirrorful/mirrorful/issues/158)
Added formatter
- husky + pretty-quick + prettier
- moved prettier from dependencies to devDependencies in packages/mirrorful
> Added functionality of code formatting on pre-commit hook

- README.md
- i18n/README.de.md
- i18n/README.sv.md
- i18n/README.tr.md
- packages/mirrorful/README.md
- `commit-activity` badge in README.md files was pointing to an incorrect link. Replaced it with the correct one.
> Replaced incorrect link in README.md files across the project

- packages/mirrorful/editor/src/components/Dashboard.tsx
- packages/mirrorful/editor/src/components/ExportSettingsModal.tsx
- packages/mirrorful/editor/src/components/Onboarding/constants.ts
- packages/mirrorful/editor/src/components/Onboarding/index.tsx
- packages/mirrorful/editor/src/components/Onboarding/pages/ExportSettings.tsx
- packages/mirrorful/editor/src/pages/api/config.ts
- packages/mirrorful/editor/src/pages/api/export.ts
- packages/mirrorful/editor/src/utils/getExportFileTypeString.ts
This PR resolves #147: It lets users select only the file types they want to be exported!
[Demo](https://drive.google.com/file/d/1j1gGfNc1pCTTrLyHK7gCDJcX274Nk_2T/view?usp=share_link) (Ugh, sorry for the Google Drive link.)
**UI changes**:
* Added an export settings modal that has a file type section for selecting export files
* Added a settings button to open the export settings modal
* Added a step to the onboarding flow for selecting file types so that the user starts with only the files they need
**API changes**:
* `/api/config` now returns the config object, not just the tokens
* `/api/export` now accepts the config object, not just the tokens
* Manually tested creating a new Mirrorful config from scratch (see demo video above) and exporting tokens
* Manually tested updating file …
> feat: add ability to select export files

- packages/mirrorful/editor/src/components/Typography/FontSizeRow.tsx
Fixes: #170 
- Adds a function that limits the fontSize to 6rem, 6em and 96px for the FontSizeRow component preview
> fix: max font size in preview

- packages/mirrorful/editor/src/components/Typography/FontSizeRow.tsx
- Refactor check for whether the fontSize is too large to return a boolean
- Show "Font size {value}{unit} too large to render." message when the fontSize is too large for FontSizeRow preview
> refactor: show font size too large message in FontSizeRow

- packages/mirrorful/editor/src/components/ColorPalette/ColorDisplay.tsx
resolves #176 
This pr sorts the lightness of a variant and sets up a base case. Extreme cases like adding a completely different color to a variant hasn't been taking into account yet.
> sort color values by lightness

- packages/mirrorful/editor/src/components/ColorPalette/AddColorSkeleton.tsx
Simplified skeleton to 'Add Color' button, as styling was inconsistent with new layout.  Another issue can be raised to put placeholders in `AddColorSkeleton.tsx` later if desired.
> Restore 'Add Color' button, as skeleton no longer matched

- packages/mirrorful/editor/src/components/ColorPalette/ColorDisplay.tsx
Change styling of variant to highlight if it matches base - bolder font, thicker border, text indicating 'base'.  Update base comparison so that all colors are upper-cased for comparison.  Proposed fix for issue #107.
> Update styling of base color variant - fixes #107

- packages/core/src/components/Dashboard/index.tsx
- packages/core/src/components/ExportSettingsModal.tsx
Not sure why flexGrow was there originally?
With flexGrow:
> Fix Color Section over sidebar issue

- packages/core/package.json
- packages/core/src/translators/toCjs.ts
- packages/core/src/translators/toJs.ts
- yarn.lock
Resolves #155.
---
This PR replaces `JSON.stringify` with `JSON5.stringify` so that property names in `.cjs`, `.js`, and `.ts` theme files only have quotations when necessary.
`theme.js` with `JSON.stringify`:
`theme.js` with `JSON5.stringify`:
> refactor: use JSON5 to stringify theme object

- packages/core/src/components/Onboarding/index.tsx
- packages/core/src/components/Onboarding/pages/Referral.tsx
- packages/mirrorful/editor/yarn.lock
- yarn.lock
We got some user feedback that on web no one is importing their theme, so we should just jump straight to the pick a color page. Also add Hackernews referral checkbox.
> feat: Straight to Color Picker on web during onboarding.

- packages/core/src/components/Onboarding/pages/ExportSettings.tsx
- packages/core/src/components/Onboarding/pages/ImportInstructions.tsx
- packages/core/src/components/Onboarding/pages/NamePrimary.tsx
- packages/core/src/components/Onboarding/pages/OtherColors.tsx
- packages/core/src/components/Onboarding/pages/PickPrimary.tsx
- packages/core/src/components/Onboarding/pages/Referral.tsx
- packages/core/src/components/Onboarding/pages/ReviewPrimary.tsx
Previously, the onboarding was not keyboard accessible - Pressing enter did not move to the next step. This commit wraps the onboarding steps in a form component and changes the button to a submit so that the whole flow is `enter`-accessible. Also to prevent default form submit behaviour, we also need to add e.preventDefault() on the button clicks
Fixes #267
> improv: wrap onboarding steps in form elements and make them keyboard accessible

- packages/core/src/components/Shadows/EditShadowModal.tsx
- packages/core/src/components/Shadows/ShadowColorPicker.tsx
resolves #257
- Changed `onChangeEnd` to `onChange` I prefer to visually see the change that I make as I'm changing the values instead of having to wait until I drop the picker to view the change. Let me know if there's a thought process behind having `onChangeEnd`
- Wrapped `codeResult` into a `useMemo` hook to prevent unnecessary re-renders and recalculations
- Uplifting all state from `ShadowColorPicker` to `EditShadowModal` to allow both components to consume the necessary state variables
- Split the input field to multiple fields that handles their own individual value
There's a lot of prop drilling in the current codebase. I know that there were some discussion around using zustand. I hope to start moving towards a state management solution as mirrorful grows :rocket:
> adjust current shadow input UI

- docs/home/export-formats/colors.mdx
- docs/home/export-formats/font-sizes.mdx
- docs/home/export-formats/shadows.mdx
Use `<CodeGroup>` Mintifly component to clean up SCSS vs CSS vs Tailwind vs JS on the export formats sections .
_kindly review it and I will be update this accordingly_
> Issue #275 docs-modification

- packages/core/src/components/ColorPalette/EditVariantModal.tsx
- packages/mirrorful/editor/yarn.lock
- yarn.lock
This PR fixes issue #307
You can now type color names without getting the invalid color error because of trailing and leading whitespaces.
> Trim whitespace on Add variant color input

- packages/core/src/components/ColorPalette/ColorDisplay.tsx
- packages/core/src/components/ColorPalette/EditVariantModal.tsx
Fix #306 
- before saving a new variant check if this name already exists to not overwrite it, if exists throw an error
- catch any errors in `EditVariantModal` that happens with the save handler and set the already existing error state to the thrown error message 
here's an example
> cannot have two variants with the same name (#306)

- .github/workflows/core.yml
- .github/workflows/package.yml
- .github/workflows/server.yml
- .github/workflows/web.yml
This will ensure that only the workflows relevant to the changes will be triggered, instead of all workflows running.
Ref:
- https://stackoverflow.com/questions/63822219/how-to-run-github-actions-workflow-only-if-the-pushed-files-are-in-a-specific-fo
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths
Fixes #355
> chore: add paths property to github action workflows

- packages/core/src/components/ColorPalette/ColorPaletteSection.tsx
Should fix [#364](https://github.com/Mirrorful/mirrorful/issues/364) by retaining the order of colors in the `colors` object.
> Retain the order of colors when renaming

- packages/eslint-plugin/README.md
- packages/eslint-plugin/package.json
NPM doesn't like relative links to a GitHub repo. Also linked directly to the NPM plugin page.
> Update ESLint plugin docs for the NPM registry

- packages/core/src/components/ColorPalette/ColorPicker.tsx
- packages/core/src/components/ColorPalette/utils.ts
We use the following logic to take care of invalid values - 
INVALID VALUE - revert back to last valid value
VALUE > 6 - trim to six characters
VALUE < 6 - Fill 0's to make it 6 characters
Fixes #405
> feat: allow the user to input hex values in color picker

- packages/core/src/components/Typography/FontWeight/EditFontWeightModal.tsx
Editing the font-weight above 900 or adding a similar weight would show error message. #416
> fix: reduced font weight allowed limits

- packages/core/src/components/Shadows/EditShadowModal.tsx
> fix: support dark mode for 'X' and 'disabled-input' in shadow modal

- packages/core/src/components/Shadows/EditShadowModal.tsx
I noticed a bug when adding a new shadow, it won't update the values on the slides or input field.
> Deleted filter function on shadow modal 

- packages/core/src/components/Sidebar/Sidebar.tsx
This PR is the first pass for issue #486
Fixes the toggle dark/light mode on mobile.
Here's how it looks 
https://github.com/Mirrorful/mirrorful/assets/94234459/174d8a7a-1fcf-49b2-9b0b-b18114ecc09b
> Fix: toggle dark/light mode on mobile

- packages/core/src/components/LoginAlert.tsx
> fix: center align the 'You are not logged in' popover on sm screens

- README.md
fixes #508 
by replacing the current link to the docs `https://www.mirrorful.com/` to `https://www.mirrorful.com/docs/home/intropage`
> 📝 Fix github readme.md docs link
